theme: jekyll-theme-so-simple
locale: it
title: "Contrade San Paolino"
description: "Associazione di rievocazione storica a Lucca: balestrieri, tamburi e molto altro"
baseurl: 
url: https://consanpaolino.org
logo: "/images/logo.png"
date_format: "%F"
read_time: true
words_per_minute: 100
mathjax: false
excerpt_separator: "<!-- more -->"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
disqus:
  shortname: consanpaolino
twitter:
  username: consanpaolino
facebook:
 publisher: 1787905061499575
 admins: 511505670
social:
  name: Contrade San Paolino
  links:
    - https://twitter.com/consanpaolino
    - https://www.facebook.com/consanpaolino
    - https://plus.google.com/+ConsanpaolinoOrg
lang: it_IT
exclude: [bin, package.json, package-lock.json, vendor, .circleci, node_modules, Gemfile, Gemfile.lock]

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:name/
markdown: kramdown
category_archive_path: "/"
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page/:num/

# Search
search_full_content: true # can have performance implications for large sites

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-youtube
  - jekyll-minifier
  - jemoji

jekyll-minifier:
  exclude: '*.html'

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true
  - scope:
      path:            "post"
    values:
      sitemap:         false
  - scope:
      path:            "page"
    values:
      sitemap:         false

# Site Author
author:
  name:
  picture:
  email: consanpaolino@gmail.com
  twitter: consanpaolino
  links:
    - title:
      url:
      icon:

# Footer Links
footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
  - title: Facebook
    url: https://fb.com/consanpaolino
    icon: fab fa-facebook-square
  - title: Twitter
    url: https://twitter.com/consanpaolino
    icon: fab fa-twitter-square
  - title: Instagram
    url: https://instagram.com/consanpaolino
    icon: fab fa-instagram
  - title: youtube
    url: https://www.youtube.com/channel/UC8fqZye7eBrSWTbd5dzyUCg
    icon: fab fa-youtube