theme: jekyll-theme-so-simple
skin: "/assets/css/skins/default.css"
locale: it-IT
lang: it-IT #jekyll-seo-tag
title: "🎯 Contrade San Paolino 🥁"
description: "Associazione di rievocazione storica a Lucca: balestrieri, musici e figuranti"
copyright: |
  <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">
    <img alt="Licenza Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/80x15.png" />
  </a><br />
  I contenuti di questo sito web sono distribuiti con Licenza <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribuzione - Condividi allo stesso modo 4.0 Internazionale</a>.<br/>
  Sito web generato con [Jekyll](https://jekyllrb.com/) e tema [so-simple-theme](https://github.com/mmistakes/so-simple-theme), sorgenti su [GitHub](https://github.com/gionn/consanpaolino).<br/>
  [Privacy](/privacy)
baseurl:
url: https://consanpaolino.org
logo: "/images/logo.jpg"
date_format: "%F"
read_time: false
words_per_minute: 80
mathjax: false
excerpt_separator: "<!-- more -->"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
disqus:
  shortname: consanpaolino
twitter:
  username: consanpaolino
facebook:
  publisher: 1787905061499575
  admins: 511505670
social:
  name: Contrade San Paolino
  links:
    - https://twitter.com/consanpaolino
    - https://www.facebook.com/consanpaolino
    - https://www.facebook.com/luccamedievale
    - https://www.instagram.com/consanpaolino/
    - https://t.me/consanpaolino
    - https://www.youtube.com/channel/UC8fqZye7eBrSWTbd5dzyUCg
exclude:
  - bin
  - package.json
  - package-lock.json
  - vendor
  - .circleci
  - node_modules
  - Gemfile
  - Gemfile.lock
  - SNIPPETS.md

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:year/:title
markdown: kramdown
category_archive_path: "/"
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page/:num/

# Search
search_full_content: true # can have performance implications for large sites

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-youtube
  - jekyll-minifier
  - jemoji
  - jekyll-last-modified-at

collections:
  competitions:
    output: true
    permalink: /:collection/:year/:month/:day/:title

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
    values:
      layout: post
      share: false
  - scope:
      path: "pages"
    values:
      layout: page
      share: false
  - scope:
      path: "_competitions"
    values:
      layout: competition
      share: false
      sitemap: false

# Site Author
author:
  name: Giovanni Toraldo
  picture:
  email: consanpaolino@gmail.com
  twitter: consanpaolino

# Footer
footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
  - title: Facebook
    url: https://fb.com/consanpaolino
    icon: fab fa-facebook-square
  - title: Twitter
    url: https://twitter.com/consanpaolino
    icon: fab fa-twitter-square
  - title: Instagram
    url: https://instagram.com/consanpaolino
    icon: fab fa-instagram
  - title: youtube
    url: https://www.youtube.com/channel/UC8fqZye7eBrSWTbd5dzyUCg
    icon: fab fa-youtube
  - title: telegram
    url: https://t.me/consanpaolino
    icon: fab fa-telegram

jekyll-minifier:
  compress_css: false
  exclude:
    - "robots.txt"
    - "atom.xml"
