theme: jekyll-theme-so-simple
locale: it
title: "Contrade San Paolino"
description: "Associazione rievocazione storica di Lucca"
baseurl: 
url: https://consanpaolino.org
logo: "/images/logo.png"
date_format: "%F"
read_time: true
words_per_minute: 100
mathjax: false
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: consanpaolino
twitter:
  username: consanpaolino

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: /page:num/

# Search
search_full_content: true # can have performance implications for large sites

# Taxonomy pages
# category_archive_path: "/categories/#"
# tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

# Site Author
author:
  name:
  picture:
  email: consanpaolino@gmail.com
  twitter: consanpaolino
  links:
    - title:
      url:
      icon:

# Footer Links
footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
  - title: Facebook
    url: https://fb.com/consanpaolino
    icon: fab fa-facebook-square
  - title: Twitter
    url: https://twitter.com/consanpaolino
    icon: fab fa-twitter-square
  - title: Instagram
    url: https://instagram.com/consanpaolino
    icon: fab fa-instagram
  - title: youtube
    url: https://www.youtube.com/channel/UC8fqZye7eBrSWTbd5dzyUCg
    icon: fab fa-youtube