version: 2
jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.3-node
        environment:
          BUNDLE_PATH: vendor/bundle
          JEKYLL_ENV: production
    resource_class: small

    working_directory: ~/repo

    steps:
      - checkout

      - run: node --version
      - run: npm --version

      - restore_cache:
          keys:
            - v1-node-{{ checksum "package-lock.json" }}
            - v1-node-

      - run: npm install npm
      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-node-{{ checksum "package-lock.json" }}

      - restore_cache:
          keys:
            - v5-dependencies-{{ checksum "Gemfile.lock" }}
            - v5-dependencies-

      - run: gem install bundler
      - run: bundle install

      - save_cache:
          paths:
            - vendor/bundle
          key: v5-dependencies-{{ checksum "Gemfile.lock" }}

      - run: bundle exec jekyll build

      - run:
          name: Test
          command: bundle exec htmlproofer ./_site --check-html --disable-external --empty_alt_ignore --allow_hash_href --assume_extension

      - run:
          name: Deploy
          command: |
            if [ "$CIRCLE_BRANCH" != "master" ]; then exit 0; fi
            git config --global user.email "circleci@gionn.net"
            git config --global user.name "circleci build"
            mkdir _site/.circleci && cp .circleci/ignore.yml _site/.circleci/config.yml
            npm run deploy
            sleep 10
            curl -sS http://www.google.com/ping?sitemap=https://consanpaolino.org/sitemap.xml
            curl -sS http://www.bing.com/ping?sitemap=https://consanpaolino.org/sitemap.xml
