version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6-node-browsers
        environment:
          BUNDLE_PATH: vendor/bundle
          JEKYLL_ENV: production

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v4-dependencies-{{ checksum "Gemfile.lock" }}

      - run: gem install bundler
      - run: bundle install
      - run: npm install gh-pages

      - save_cache:
          paths:
            - vendor/bundle
          key: v4-dependencies-{{ checksum "Gemfile.lock" }}

      - run: bundle exec jekyll build

      - run:
          name: Test
          command: bundle exec htmlproofer ./_site --check-html --disable-external --empty_alt_ignore --allow_hash_href --assume_extension

      - run:
          name: Deploy
          command: |
            if [ "$CIRCLE_BRANCH" != "master" ]; then exit 0; fi
            git config --global user.email "circleci@gionn.net"
            git config --global user.name "circleci build"
            mkdir _site/.circleci && cp .circleci/ignore.yml _site/.circleci/config.yml
            npm run deploy
            sleep 10
            curl -sS http://www.google.com/ping?sitemap=https://consanpaolino.org/sitemap.xml
            curl -sS http://www.bing.com/ping?sitemap=https://consanpaolino.org/sitemap.xml
