name: Validate & Publish

on:
  push:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install node dependencies
        run: npm ci

      - name: Add node bin to PATH
        run: echo "$PWD/node_modules/.bin" >> $GITHUB_PATH

      - name: Validate markdown
        run: markdownlint -c .markdownlint.json _posts pages

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Build
        run: bundle exec jekyll build
      
      - name: Validate HTML output
        run: bundle exec htmlproofer ./_site --ignore-missing-alt --disable-external --enforce-https false --allow-missing-href true

      - name: Setup Pages
        if: github.ref_name == 'master'
        uses: actions/configure-pages@v3

      - name: Upload artifact
        if: github.ref_name == 'master'
        uses: actions/upload-pages-artifact@v2
        with:
          path: '_site'


  deploy:
    if: github.ref_name == 'master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
      - name: Ping search indexes
        run: |
          curl -sS http://www.google.com/ping?sitemap=https://consanpaolino.org/sitemap.xml
          curl -sS http://www.bing.com/ping?sitemap=https://consanpaolino.org/sitemap.xml
