name: Optimize jpg files

on:
  push:
    paths:
      - '**.jpg'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37

      - name: Install jpegoptim
        run: sudo apt-get install -y jpegoptim

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.added_files }}; do
            echo "Found changed: $file"
            if [[ "$file" = *".jpg"* ]]; then
              jpegoptim "$file"
            fi
          done

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply jpegoptim changes
